---
docker_users:
- "{{secret_unix_name}}"
torrenter_data_mount: /mnt/expansion
torrenter_backup_mount: /mnt/synology_canvio
# --- Systemd Mount Dependencies ---
# Boolean flags to control whether a mount is considered a systemd dependency
torrenter_data_mount_is_systemd_managed: true
torrenter_backup_mount_is_systemd_managed: true
# --- Network Mounts (NFS/SMB) ---
# A dictionary of all available network shares the torrenter might need.
network_mounts_definitions:
  synology_canvio:
    path: /mnt/synology_canvio
    src: 192.168.1.253:/volumeUSB2/usbshare
    fstype: nfs
    opts: defaults,noatime,bg

# A list of keys from the above dictionary to actually mount for this group.
network_mounts_enabled:
  - synology_canvio

# --- Rsync Backup Target ---
rsync_service_name: "rsync"
backup_target_rsync_module_name: "synology_target"
backup_target_rsync_base_path: "/mnt/expansion/synology_vault"
backup_target_rsync_comment: "Backup Target for Synology"
backup_target_rsync_uid: "1000"
backup_target_rsync_gid: "1000"
backup_target_rsync_user: "synology"
backup_target_rsync_allowed_hosts: "192.168.0.0/16"

# --- NUT Client Configuration ---
nut_mode: netclient
nut_upsmon_extra: "MONITOR ups@192.168.1.253 1 monuser {{ nut_mon_password }} slave"
nut_services:
  - nut-monitor.service
  - nut.target
nut_ups: [] # Explicitly define no local UPS devices

# --- Docker Daemon Configuration ---
docker_daemon_options:
  log-driver: "journald"

# --- Tailscale Configuration ---
tailscale_oauth_ephemeral: false
tailscale_args: "--hostname raspberrypi"



